### ISSUE TITLE
How  transform your code to multi nodes？

### ISSUE THREAD

**Issue by dreamlychina** [soumyadipghosh/eventgrad#1]
thanks for your amazing work, i want change your code using multi cpu nodes. Do you have some advice???

**Comment by soumyadipghosh** [comment]
Hi @dreamlychina , Thanks for your interest. The code should work with multi cpu nodes. In MPI, you can launch using `mpirun -np ${num_proc}` where num_proc can be the total number of cores on multiple nodes.
